name: deeplook_notebooks
channels:
- defaults
dependencies:
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_0
- conda-forge::basemap=1.0.8.dev0=np111py35_2
- conda-forge::ca-certificates=2016.9.26=0
- conda-forge::certifi=2016.9.26=py35_0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::entrypoints=0.2.2=py35_0
- conda-forge::freetype=2.6.3=1
- conda-forge::geopy=1.11.0=py35_0
- conda-forge::geos=3.4.2=2
- conda-forge::ipykernel=4.5.0=py35_0
- conda-forge::ipython=5.1.0=py35_1
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::ipywidgets=5.2.2=py35_2
- conda-forge::jinja2=2.8=py35_1
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter_client=4.4.0=py35_0
- conda-forge::jupyter_console=5.0.0=py35_0
- conda-forge::jupyter_core=4.2.0=py35_0
- conda-forge::libpng=1.6.26=0
- conda-forge::libsodium=1.0.10=0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::matplotlib=1.5.3=np111py35_2
- conda-forge::mistune=0.7.3=py35_0
- conda-forge::nbconvert=4.2.0=py35_0
- conda-forge::nbformat=4.1.0=py35_0
- conda-forge::ncurses=5.9=9
- conda-forge::notebook=4.2.3=py35_0
- conda-forge::openssl=1.0.2h=2
- conda-forge::pandas=0.19.1=np111py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::pip=9.0.1=py35_0
- conda-forge::prompt_toolkit=1.0.9=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.1.3=py35_1
- conda-forge::pyparsing=2.1.10=py35_0
- conda-forge::pyproj=1.9.5.1=py35_0
- conda-forge::pyqt=4.11.4=py35_1
- conda-forge::pyshp=1.2.10=py35_0
- conda-forge::python=3.5.2=2
- conda-forge::python-dateutil=2.5.3=py35_0
- conda-forge::pytz=2016.7=py35_0
- conda-forge::pyzmq=16.0.1=py35_0
- conda-forge::qtconsole=4.2.1=py35_1
- conda-forge::readline=6.2=0
- conda-forge::setuptools=28.8.0=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_0
- conda-forge::six=1.10.0=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::terminado=0.6=py35_0
- conda-forge::tk=8.5.19=0
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::traitlets=4.3.1=py35_0
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::widgetsnbextension=1.2.6=py35_3
- conda-forge::xz=5.2.2=0
- conda-forge::zeromq=4.1.5=0
- conda-forge::zlib=1.2.8=3
- jupyter=1.0.0=py35_3
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- qt=4.8.7=4
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - prompt-toolkit==1.0.9
